language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
   #Uses miniconda installation of scientific python packages instead of building from source
   #or using old versions supplied by apt-get. Source: https://gist.github.com/dan-blanchard/7045057
   - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.3.0-Linux-x86_64.sh -O miniconda.sh; fi
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda/bin:$PATH
   - conda update --yes conda
   - sudo apt-get update -qq
   - sudo apt-get install -qq build-essential libgsl0-dev bedtools
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy biopython pandas pip scikit-learn docutils sphinx jinja2
  - pip install bcbio-gff
  - python setup.py install
# command to run tests
script: nosetests

branches:
  only:
    - master
    - travis_tryout
    - develop
